version: 0.0
os: linux

files: 
  - source: /target/hello-world-maven.war
    destination: /opt/tomcat/webapps
    overwrite: true

permissions: 
  - object: / 
    pattern: "**" 
    mode: 755
    owner: tomcat 
    group: tomcat

hooks:
  ApplicationStop:
    - location: scripts/server_stop_clean.sh
      timeout: 180
      runas: root

  ApplicationStart:
    - location: scripts/server_start.sh   
      timeout: 120
      runas: root
